# Generated by Django 3.2.23 on 2024-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_chef_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Snack', 'Snack'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=50),
        ),
    ]
