# Generated by Django 3.2.23 on 2024-01-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_chef_recipe_owner'),
        ('RecipeLike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipelike',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeLikes', to='recipe.recipe'),
        ),
    ]
