# Generated by Django 3.2.23 on 2024-01-18 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quicksnap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuicksnapComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quicksnap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quicksnap.quicksnap')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
