# Generated by Django 3.2.23 on 2024-01-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quicksnap', '0001_initial'),
        ('QuicksnapComments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicksnapcomment',
            name='quicksnap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuicksnapComments', to='quicksnap.quicksnap'),
        ),
    ]
