# Generated by Django 3.2.23 on 2024-01-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_chef_recipe_owner'),
        ('RecipeComments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeComments', to='recipe.recipe'),
        ),
    ]
